### ISSUE TITLE
get onto pypi

### ISSUE THREAD

**Issue by buckle2000** [jribbens/unsafe#4]
the name "unsafe" is still avaliable on pypi

**Comment by jribbens** [comment]
As I mentioned on the python-dev list, I won't be releasing this as an easy-to-install package. I think that the basic idea behind this code is valid, but the mailing list thread did prove that at the very least you have to be extremely careful how you use it. I'm leaving it up on github as an example for people to experiment with, but I don't want to encourage anyone to actually rely on it for anything.
