### ISSUE TITLE
error on safe_namespace

### ISSUE THREAD

**Issue by buckle2000** [jribbens/unsafe#5]
![pic](https://cloud.githubusercontent.com/assets/10850402/14603927/45fce9e8-05a3-11e6-8409-d4e3dcba246c.PNG)

`b` is constructed as followed:

```
b = unsafe.safe_compile("""def a():
        return 1
""",'','exec')
```

**Comment by jribbens** [comment]
Note that there was a bug which your issue has exposed and I have fixed, but `safe_eval()` and `safe_exec()` take strings, not pre-compiled code objects. They call `safe_compile()` automatically within themselves.
